//Create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "prima",
    "email": "prima@gmail.com",
    "password": "1234",
    "confPassword": "1234",
    "role": "user"
}

###
//get all users
GET http://localhost:5000/users

###
//get single user
GET http://localhost:5000/users/43b70f9e-f878-4bb4-adea-56c85173ec6b

###
//update user
PATCH  http://localhost:5000/users/6a6005f1-a8d7-4e66-865d-d988fd0c2b3c
Content-Type: application/json

{
    "name": "prima updated",
    "email": "prima@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
//delete user
DELETE http://localhost:5000/users/43b70f9e-f878-4bb4-adea-56c85173ec6b

###
//Login User
POST http://localhost:5000/login
Content-Type: application/json

{    
    "email": "prima@gmail.com",
    "password": "1234"
}

###
//get logged in user data
GET http://localhost:5000/me

###
//logout
DELETE http://localhost:5000/logout

###
//get all products
GET http://localhost:5000/products

###
//create a product
POST http://localhost:5000/products
Content-Type: application/json

{    
    "name": "produk 4",
    "price": 1234
}